// <auto-generated />
namespace CapStone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hellomodelmethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hellomodelmethod));
        
        string IMigrationMetadata.Id
        {
            get { return "201802271503092_hello model method"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
