// <auto-generated />
namespace CapStone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hellotargetdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hellotargetdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201803020320057_hello target date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
